version: '3'
services:
  ipfs:
    container_name: ipfs
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.ipfs         
    ports:
      - "8080:8080"
      - "50001:5001"
      - "40001:4001"
      - "30000:3000"
    networks:
      - ipfs  
    volumes:
      - ipfs:/app/ipfs

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - ipfs

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    networks:
      - ipfs      

volumes:
  ipfs:
  grafana-data:  

networks:
  ipfs:
    driver: bridge  
