{
 "title": "IPFS Metrics Dashboard",
 "tags": [ "ipfs" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "memstats_heap_alloc_bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(go_memstats_heap_alloc_bytes{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc errors total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(flatfs_datastore_gc_errors_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 10 },
   "targets": [
    { "expr": "ipfs_p2p_peers_total", "legendFormat": "Connected Peers" }
   ]
  },
  {
   "title": "avg go threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 15 },
   "targets": [
    { "expr": "avg(go_threads{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "datastore query total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(flatfs_datastore_query_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}